# Generated by Django 4.2.16 on 2024-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0004_alter_animal_adotante_alter_animal_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('doador', 'Doador'), ('adotante', 'Adotante'), ('admin', 'Administrador')], max_length=10),
        ),
    ]
