# Generated by Django 4.2.16 on 2024-11-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0005_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_animais/'),
        ),
    ]
