# Generated by Django 4.2.16 on 2024-12-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0007_alter_adocao_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='adote.animal')),
            ],
        ),
    ]
