# Generated by Django 4.2.16 on 2024-12-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0008_interesseadocao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaAnimal',
        ),
    ]
